### ISSUE TITLE
DB table is used by multiple models on Django 2.2

### ISSUE THREAD

**Issue by clickera** [pmaigutyak/mp-turbosms#1]
Hi. I have updated my Django to version 2.2, and I got error when I try to run django server:
`table_name: (models.E028) db_table 'table_name' is used by multiple models: turbosms.SMS, turbosms.SMSRecord.`

**Comment by pmaigutyak** [comment]
Hi, I don't have any project with this version of Django. Did you fix this issue on your project ?

**Comment by clickera** [comment]
Hi. Yes, I had fix it. I just remove additional model.

**Comment by pmaigutyak** [comment]
@clickera I'll do the same. Wait for 3.3 release. I'll push it after tests and let you know.

**Comment by pmaigutyak** [comment]
@clickera I've uploaded django-turbosms version 3.3 with fix for django 2.2 version.

**Comment by clickera** [comment]
Hi. Thank you!
